/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedDashboardTeacherRouteImport } from './routes/_authenticated/dashboard/teacher'
import { Route as AuthenticatedDashboardStudentRouteImport } from './routes/_authenticated/dashboard/student'
import { Route as AuthenticatedTeacherReviewRoomIdRouteImport } from './routes/_authenticated/teacher/review.$roomId'
import { Route as AuthenticatedPlayRoomIdResultsRouteImport } from './routes/_authenticated/play/$roomId/results'
import { Route as AuthenticatedPlayRoomIdBriefingRouteImport } from './routes/_authenticated/play/$roomId/briefing'
import { Route as AuthenticatedPlayRoomIdBossRouteImport } from './routes/_authenticated/play/$roomId/boss'
import { Route as AuthenticatedPlayRoomIdRoomRoomNumberRouteImport } from './routes/_authenticated/play/$roomId/room/$roomNumber'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardTeacherRoute =
  AuthenticatedDashboardTeacherRouteImport.update({
    id: '/dashboard/teacher',
    path: '/dashboard/teacher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentRoute =
  AuthenticatedDashboardStudentRouteImport.update({
    id: '/dashboard/student',
    path: '/dashboard/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherReviewRoomIdRoute =
  AuthenticatedTeacherReviewRoomIdRouteImport.update({
    id: '/teacher/review/$roomId',
    path: '/teacher/review/$roomId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayRoomIdResultsRoute =
  AuthenticatedPlayRoomIdResultsRouteImport.update({
    id: '/play/$roomId/results',
    path: '/play/$roomId/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayRoomIdBriefingRoute =
  AuthenticatedPlayRoomIdBriefingRouteImport.update({
    id: '/play/$roomId/briefing',
    path: '/play/$roomId/briefing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayRoomIdBossRoute =
  AuthenticatedPlayRoomIdBossRouteImport.update({
    id: '/play/$roomId/boss',
    path: '/play/$roomId/boss',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayRoomIdRoomRoomNumberRoute =
  AuthenticatedPlayRoomIdRoomRoomNumberRouteImport.update({
    id: '/play/$roomId/room/$roomNumber',
    path: '/play/$roomId/room/$roomNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/teacher': typeof AuthenticatedDashboardTeacherRoute
  '/play/$roomId/boss': typeof AuthenticatedPlayRoomIdBossRoute
  '/play/$roomId/briefing': typeof AuthenticatedPlayRoomIdBriefingRoute
  '/play/$roomId/results': typeof AuthenticatedPlayRoomIdResultsRoute
  '/teacher/review/$roomId': typeof AuthenticatedTeacherReviewRoomIdRoute
  '/play/$roomId/room/$roomNumber': typeof AuthenticatedPlayRoomIdRoomRoomNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/teacher': typeof AuthenticatedDashboardTeacherRoute
  '/play/$roomId/boss': typeof AuthenticatedPlayRoomIdBossRoute
  '/play/$roomId/briefing': typeof AuthenticatedPlayRoomIdBriefingRoute
  '/play/$roomId/results': typeof AuthenticatedPlayRoomIdResultsRoute
  '/teacher/review/$roomId': typeof AuthenticatedTeacherReviewRoomIdRoute
  '/play/$roomId/room/$roomNumber': typeof AuthenticatedPlayRoomIdRoomRoomNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/_authenticated/dashboard/teacher': typeof AuthenticatedDashboardTeacherRoute
  '/_authenticated/play/$roomId/boss': typeof AuthenticatedPlayRoomIdBossRoute
  '/_authenticated/play/$roomId/briefing': typeof AuthenticatedPlayRoomIdBriefingRoute
  '/_authenticated/play/$roomId/results': typeof AuthenticatedPlayRoomIdResultsRoute
  '/_authenticated/teacher/review/$roomId': typeof AuthenticatedTeacherReviewRoomIdRoute
  '/_authenticated/play/$roomId/room/$roomNumber': typeof AuthenticatedPlayRoomIdRoomRoomNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/generate'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/play/$roomId/boss'
    | '/play/$roomId/briefing'
    | '/play/$roomId/results'
    | '/teacher/review/$roomId'
    | '/play/$roomId/room/$roomNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/generate'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/play/$roomId/boss'
    | '/play/$roomId/briefing'
    | '/play/$roomId/results'
    | '/teacher/review/$roomId'
    | '/play/$roomId/room/$roomNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/generate'
    | '/_authenticated/dashboard/student'
    | '/_authenticated/dashboard/teacher'
    | '/_authenticated/play/$roomId/boss'
    | '/_authenticated/play/$roomId/briefing'
    | '/_authenticated/play/$roomId/results'
    | '/_authenticated/teacher/review/$roomId'
    | '/_authenticated/play/$roomId/room/$roomNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/teacher': {
      id: '/_authenticated/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof AuthenticatedDashboardTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student': {
      id: '/_authenticated/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthenticatedDashboardStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/review/$roomId': {
      id: '/_authenticated/teacher/review/$roomId'
      path: '/teacher/review/$roomId'
      fullPath: '/teacher/review/$roomId'
      preLoaderRoute: typeof AuthenticatedTeacherReviewRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$roomId/results': {
      id: '/_authenticated/play/$roomId/results'
      path: '/play/$roomId/results'
      fullPath: '/play/$roomId/results'
      preLoaderRoute: typeof AuthenticatedPlayRoomIdResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$roomId/briefing': {
      id: '/_authenticated/play/$roomId/briefing'
      path: '/play/$roomId/briefing'
      fullPath: '/play/$roomId/briefing'
      preLoaderRoute: typeof AuthenticatedPlayRoomIdBriefingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$roomId/boss': {
      id: '/_authenticated/play/$roomId/boss'
      path: '/play/$roomId/boss'
      fullPath: '/play/$roomId/boss'
      preLoaderRoute: typeof AuthenticatedPlayRoomIdBossRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$roomId/room/$roomNumber': {
      id: '/_authenticated/play/$roomId/room/$roomNumber'
      path: '/play/$roomId/room/$roomNumber'
      fullPath: '/play/$roomId/room/$roomNumber'
      preLoaderRoute: typeof AuthenticatedPlayRoomIdRoomRoomNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedDashboardStudentRoute: typeof AuthenticatedDashboardStudentRoute
  AuthenticatedDashboardTeacherRoute: typeof AuthenticatedDashboardTeacherRoute
  AuthenticatedPlayRoomIdBossRoute: typeof AuthenticatedPlayRoomIdBossRoute
  AuthenticatedPlayRoomIdBriefingRoute: typeof AuthenticatedPlayRoomIdBriefingRoute
  AuthenticatedPlayRoomIdResultsRoute: typeof AuthenticatedPlayRoomIdResultsRoute
  AuthenticatedTeacherReviewRoomIdRoute: typeof AuthenticatedTeacherReviewRoomIdRoute
  AuthenticatedPlayRoomIdRoomRoomNumberRoute: typeof AuthenticatedPlayRoomIdRoomRoomNumberRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedDashboardStudentRoute: AuthenticatedDashboardStudentRoute,
  AuthenticatedDashboardTeacherRoute: AuthenticatedDashboardTeacherRoute,
  AuthenticatedPlayRoomIdBossRoute: AuthenticatedPlayRoomIdBossRoute,
  AuthenticatedPlayRoomIdBriefingRoute: AuthenticatedPlayRoomIdBriefingRoute,
  AuthenticatedPlayRoomIdResultsRoute: AuthenticatedPlayRoomIdResultsRoute,
  AuthenticatedTeacherReviewRoomIdRoute: AuthenticatedTeacherReviewRoomIdRoute,
  AuthenticatedPlayRoomIdRoomRoomNumberRoute:
    AuthenticatedPlayRoomIdRoomRoomNumberRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
